name: Deploy Backend

on:
  push:
    branches: [ main ]  # 当main分支有推送时触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # 进入项目目录
            cd /project/sakana-resume-backend
            
            # 拉取最新代码
            git pull origin main
            
            # 获取当前时间作为版本号
            VERSION=$(date +%Y%m%d_%H%M%S)
            
            # 停止并删除旧容器
            docker-compose down || true
            
            # 构建新镜像（带版本号）
            docker-compose build
            
            # 启动新容器
            docker-compose up -d
            
            # 清理旧镜像（保留最近5个版本）
            docker images sakana-resume-backend --format "{{.Tag}}" | grep -v "latest" | sort -r | tail -n +6 | xargs -r -I {} docker rmi sakana-resume-backend:{} || true 